# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d44f4df66a8b578a4ca0205aa88aedf4a7ef4f078a5efc4f71955e3c6fe2198ad36fae318638b3f95d414460ebd58c6bd0b2555c73a966b1db7a416b8fa1874

test:
  secret_key_base: 6282ef8c201002aa370b69120b729944d1909879daa46ea01cb7b8b1444ceac844df6ea990689f85f0d0f33a3ab9881ac149aa2b1baa55099a5be2c4d1bcf406

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
